// This file is auto-generated by @hey-api/openapi-ts

export type Body_insert_api_datalake__post = {
    file: (Blob | File);
};

export type Body_request_api_model_train_post = {
    failures: (Blob | File);
    results: (Blob | File);
    status: (Blob | File);
    tags?: Array<(string)>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type KNR = {
    knr: string;
    data: {
        [key: string]: unknown;
    };
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type HealthCheckApiHealthGetResponse = ({
    [key: string]: unknown;
});

export type GetDataApiKeysGetResponse = ({
    [key: string]: unknown;
});

export type CreateKeyApiKeysPostResponse = ({
    [key: string]: unknown;
});

export type PredictApiKnrPredictKnrGetData = {
    knr: string;
};

export type PredictApiKnrPredictKnrGetResponse = (unknown);

export type ListKnrsApiKnrGetResponse = (unknown);

export type NewKnrApiKnrPostData = {
    requestBody: KNR;
};

export type NewKnrApiKnrPostResponse = (unknown);

export type GetKnrApiKnrKnrGetData = {
    knr: string;
};

export type GetKnrApiKnrKnrGetResponse = (unknown);

export type GetLastKnrApiKnrLastProcessedGetResponse = (unknown);

export type GetListApiDatalakeGetResponse = (unknown);

export type InsertApiDatalakePostData = {
    formData: Body_insert_api_datalake__post;
};

export type InsertApiDatalakePostResponse = (unknown);

export type GetTableApiDatalakeTableNameGetData = {
    knrQuery?: (string | null);
    page?: number;
    perPage?: number;
    tableName: string;
};

export type GetTableApiDatalakeTableNameGetResponse = (unknown);

export type DeleteTableApiDatalakeTableNameDeleteData = {
    tableName: string;
};

export type DeleteTableApiDatalakeTableNameDeleteResponse = (unknown);

export type RequestApiModelTrainPostData = {
    formData: Body_request_api_model_train_post;
};

export type RequestApiModelTrainPostResponse = (unknown);

export type ListModelsApiModelGetResponse = (unknown);

export type DownloadModelApiModelDownloadModelIdGetData = {
    modelId: string;
};

export type DownloadModelApiModelDownloadModelIdGetResponse = (unknown);

export type DeleteModelApiModelModelIdDeleteData = {
    modelId: string;
};

export type DeleteModelApiModelModelIdDeleteResponse = (unknown);

export type SelectModelApiModelSelectModelIdPostData = {
    modelId: string;
};

export type SelectModelApiModelSelectModelIdPostResponse = (unknown);

export type SelectedModelApiModelSelectedGetResponse = (unknown);

export type GetCheckupTimeChartApiChartsCheckupTimeGetResponse = (unknown);

export type GetFreqErrosChartApiChartsFreqErrosGetResponse = (unknown);